# Workflow for the CI/CD pipeline for the Python app

name: CI/CD Pipeline Python App
run-name: ${{ github.actor }} - CI/CD Pipeline Python App

# Controls when the workflow will run
on:
  # Triggers the workflow
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs to run
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
      # Configures Python version
      - name: Config Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"
      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      # Run lint pylint
      - name: Run Lint Pylint
        run: |
          pylint src/calculator.py
      # Run tests pytest
      - name: Run tests
        run: |
          python3 -m pytest --cov=src --cov-report=xml:docs-covtests-reports/coverage.xml
          coverage run -m pytest tests/test_calculator.py
          coverage html -d ./docs-covtests-reports
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: docs-covtests-reports
          path: ./docs-covtests-reports
      # Run docs pdoc
      - name: Run docs
        run: |
          pdoc src/calculator.py -o ./docs-html
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs-html
          path: ./docs-html
